= Feed API
:doctype: book
:icons: font
:source-highlighter: highlightjs
:toc: left
:toc-title: Feed API Docs
:toclevels: 2
:sectlinks:
ifndef::snippets[]
:snippets: ../../../build/generated-snippets
endif::[]
ifndef::page[]
:page: src/docs/asciidoc
endif::[]


[[피드생성-API]]
== *1. 피드 생성 API*

=== *1-1* 성공

operation::feed-create-api-test/정상적으로_피드를_생성한다[snippets='http-request,request-headers,request-part-jsonData-fields,http-response,response-headers']

=== *1-2* 실패 - 카테고리 아이디가 유효하지 않음

operation::feed-create-api-test/피드_생성시_유효하지_않은_카테고리_아이디를_입력하면_예외가_발생한다[snippets='http-request,http-response']

=== *1-3* 실패 - 카테고리를 입력하지 않음

operation::feed-create-api-test/피드_생성시_카테고리_아이디를_입력하지_않으면_예외가_발생한다[snippets='http-request,http-response']

=== *1-4* 실패 - 피드 제목의 길이가 40보다 큼

operation::feed-create-api-test/피드_생성시_피드_제목의_길이가_40보다_크면_예외가_발생한다[snippets='http-request,http-response']

=== *1-5* 실패 - 피드 제목을 입력하지 않음

operation::feed-create-api-test/피드_생성시_피드_제목을_입력하지_않으면_예외가_발생한다[snippets='http-request,http-response']

=== *1-6* 실패 - 피드 소개글의 길이가 150보다 큼

operation::feed-create-api-test/피드_생성시_피드_소개글의_길이가_150보다_크면_예외가_발생한다[snippets='http-request,http-response']

=== *1-7* 실패 - 피드 소개글을 입력하지 않음

operation::feed-create-api-test/피드_생성시_피드_소개글을_입력하지_않으면_예외가_발생한다[snippets='http-request,http-response']

=== *1-8* 실패 - 피드 본문의 길이가 2000보다 큼

operation::feed-create-api-test/피드_생성시_피드_본문의_길이가_2000보다_크면_예외가_발생한다[snippets='http-request,http-response']

=== *1-9* 실패 - 피드 추천 소요 기간이 0보다 작거나 1000보다 큼

operation::feed-create-api-test/피드_생성시_피드_추천_소요기간이_0보다_작거나_1000보다_크면_예외가_발생한다[snippets='http-request,http-response']

=== *1-10* 실패 - 피드 추천 소요 기간을 입력하지 않음

operation::feed-create-api-test/피드_생성시_피드_추천_소요기간을_입력하지_않으면_예외가_발생한다[snippets='http-request,http-response']

=== *1-11* 실패 - 피드 노드의 제목의 길이가 40보다 큼

operation::feed-create-api-test/피드_생성시_피드_노드의_제목의_길이가_40보다_크면_예외가_발생한다[snippets='http-request,http-response']

=== *1-12* 실패 - 피드 노드의 제목을 입력하지 않음

operation::feed-create-api-test/피드_생성시_피드_노드의_제목을_입력하지_않으면_예외가_발생한다[snippets='http-request,http-response']

=== *1-13* 실패 - 피드 노드의 설명의 길이가 2000보다 큼

operation::feed-create-api-test/피드_생성시_피드_노드의_설명의_길이가_2000보다_크면_예외가_발생한다[snippets='http-request,http-response']

=== *1-14* 실패 - 피드 노드의 설명을 입력하지 않음

operation::feed-create-api-test/피드_생성시_피드_노드의_설명을_입력하지_않으면_예외가_발생한다[snippets='http-request,http-response']

=== *1-15* 실패 - 피드 태그의 이름에 중복이 있음

operation::feed-create-api-test/피드_생성시_중복된_태그_이름이_있으면_예외가_발생한다[snippets='http-request,http-response']

=== *1-16* 실패 - 피드 태그의 개수가 5개 초과임

operation::feed-create-api-test/피드_생성시_태그_개수가_5개_초과면_예외가_발생한다[snippets='http-request,http-response']

=== *1-17* 실패 - 피드 태그의 이름이 1자 미만 10자 초과임

operation::feed-create-api-test/피드_생성시_태그_이름이_1미만_10초과면_예외가_발생한다[snippets='http-request,http-response']

=== *1-18* 실패 - 피드 생성 시 회원이 존재하지 않음

operation::feed-create-api-test/피드_생성시_존재하지_않은_회원이면_예외가_발생한다[snippets='http-request,http-response']

[[피드목록조회-API]]
== *2. 피드 목록 조회 API*

=== *2-1* 성공

operation::feed-read-api-test/피드_목록을_조건에_따라_조회한다[snippets='http-request,query-parameters,http-response,response-fields']

=== *2-2* 실패 - 카테고리 아이디가 유효하지 않음

operation::feed-read-api-test/피드_목록_조회시_유효하지_않은_카테고리_아이디를_보내면_예외가_발생한다[snippets='http-request,http-response']

=== *2-3* 실패 - 사이즈 값을 전송하지 않음

operation::feed-read-api-test/피드_목록_조회시_사이즈_값을_전송하지_않으면_예외가_발생한다[snippets='http-request,http-response']

[[피드카테고리목록조회-API]]
== *3. 피드 카테고리 목록 조회 API*

=== *3-1* 성공

operation::feed-read-api-test/피드_카테고리_목록을_조회한다[snippets='http-request,http-response,response-fields']

[[피드단일조회-API]]
== *4. 피드 단일 조회 API*

=== *4-1* 성공

operation::feed-read-api-test/단일_피드_정보를_조회한다[snippets='http-request,path-parameters,http-response,response-fields']

=== *4-2* 실패 - 피드 아이디가 유효하지 않음

operation::feed-read-api-test/존재하지_않는_피드_아이디로_요청_시_예외를_반환한다[snippets='http-request,http-response']

[[피드검색-API]]
== *5. 피드 검색 + 필터링 API*

=== *5-1* 성공

operation::feed-read-api-test/피드를_조건별로_검색한다[snippets='http-request,query-parameters,http-response,response-fields']

=== *5-2* 실패

operation::feed-read-api-test/피드_검색시_사이즈_값을_전송하지_않으면_예외가_발생한다[snippets='http-request,http-response']

[[피드신청서생성-API]]
== *6. 피드 신청서 생성 API*

=== *6-1* 성공

operation::feed-create-api-test/피드의_신청서를_생성한다[snippets='http-request,path-parameters,request-headers,request-fields,http-response']

=== *6-2* 실패 - 유효하지 않은 피드 아이디인 경우

operation::feed-create-api-test/피드_신청서_생성시_존재하지_않은_피드이면_예외가_발생한다[snippets='http-request,http-response']

=== *6-3* 실패 - 신청서 내용이 1000자가 넘는 경우

operation::feed-create-api-test/피드_신청서_생성시_내용이_1000자가_넘으면_예외가_발생한다[snippets='http-request,http-response']

=== *6-4* 실패 - 해당 피드에 이미 신청서를 보낸 적이 있는 경우

operation::feed-create-api-test/피드_신청서_생성시_이미_신청서를_보낸적_있으면_예외가_발생한다[snippets='http-request,http-response']

=== *6-5* 실패 - 해당 피드의 생성자가 신청서를 보낸 경우

operation::feed-create-api-test/피드_신청서_생성시_피드_생성자가_신청서를_보내려고_하면_예외가_발생한다[snippets='http-request,http-response']

[[프로젝트참가요청허용-API]]
== *7. 프로젝트 참가 요청 허용 API*

=== *7-1* 성공

operation::feed-create-api-test/프로젝트_참가_요청을_허용한다[snippets='http-request,request-headers,http-response']

=== *7-2* 실패 - 프로젝트가 존재하지 않는 경우

operation::feed-create-api-test/존재하지_않는_프로젝트에_대한_참가_요청은_실패한다[snippets='http-request,http-response']

=== *7-3* 실패 - 제한 인원이 가득 찬 경우

operation::feed-create-api-test/제한_인원이_가득_찬_프로젝트에_대한_참가_요청은_실패한다[snippets='http-request,http-response']

=== *7-3* 실패 - 이미 프로젝트에 참가 한 경우

operation::feed-create-api-test/이미_참여한_프로젝트에_대한_참가_요청은_실패한다[snippets='http-request,http-response']

[[사용자피드조회-API]]
== *8. 사용자 피드 조회 API*

=== *8-1* 성공

operation::feed-read-api-test/사용자가_생성한_피드를_조회한다[snippets='http-request,request-headers,query-parameters,http-response,response-fields']

=== *8-2* 실패 - 존재하지 않는 회원인 경우

operation::feed-read-api-test/사용자가_생성한_피드를_조회할_때_존재하지_않는_회원이면_예외가_발생한다[snippets='http-request,http-response,response-fields']

[[피드의프로젝트조회-API]]
== *9. 피드의 프로젝트 조회 API*

=== *9-1* 성공

operation::feed-read-api-test/피드의_프로젝트를_조회한다[snippets='http-request,http-response,response-fields']

=== *9-2* 실패 - 존재하지 않는 피드인 경우

operation::feed-read-api-test/피드의_프로젝트를_조회할_때_피드가_존재하지_않으면_예외_발생[snippets='http-request,http-response,response-fields']

[[피드신청서조회-API]]
== *10. 피드의 신청서 목록 조회 API*

=== *10-1* 성공

operation::feed-read-api-test/피드의_신청서들을_조회한다[snippets='http-request,http-response,path-parameters,query-parameters,response-fields']

=== *10-1* 실패 - 존재하지 않는 피드인 경우

operation::feed-read-api-test/피드_신청서_조회_시_유효하지_않은_피드_아이디일_경우_예외를_반환한다[snippets='http-request,http-response,path-parameters,query-parameters,response-fields']

=== *10-2* 실패 - 피드 생성자와 일치 하지 않을 경우

operation::feed-read-api-test/피드_신청서_조회_시_피드_생성자와_일치하지_않은_생성자일_경우_예외를_반환한다[snippets='http-request,http-response,path-parameters,query-parameters,response-fields']

[[피드삭제-API]]
== *10. 피드 삭제 API*

=== *11-1* 성공

operation::feed-create-api-test/정상적으로_피드를_삭제한다[snippets='http-request,path-parameters,http-response']

=== *11-2* 실패 - 존재하지 않는 피드인 경우

operation::feed-create-api-test/피드_삭제시_존재하지_않는_피드인_경우_예외가_발생한다[snippets='http-request,http-response,response-fields']

=== *11-3* 실패 - 자신이 생성한 피드이 아닌 경우

operation::feed-create-api-test/피드_삭제시_자신이_생성한_피드이_아닌_경우_예외가_발생한다[snippets='http-request,http-response,response-fields']

[[피드카테고리생성-API]]
== *12. 피드 카테고리 생성 API*

=== *12-1* 성공

operation::feed-create-api-test/정상적으로_피드_카테고리를_생성한다[snippets='http-request,request-fields,http-response']

=== *12-2* 피드 카테고리 생성 시 카테고리 이름이 빈값일 경우

operation::feed-create-api-test/피드_카테고리_생성_시_카테고리_이름이_빈값일_경우[snippets='http-request,request-fields,http-response']

=== *12-3* 피드 카테고리 생성 시 카테고리 이름이 10자 초과일 경우

operation::feed-create-api-test/피드_카테고리_생성_시_카테고리_이름이_10자_초과일_경우[snippets='http-request,request-fields,http-response']

=== *12-4* 피드 카테고리 생성 시 카테고리 이름이 중복될 경우

operation::feed-create-api-test/피드_카테고리_생성_시_카테고리_이름이_중복될_경우[snippets='http-request,request-fields,http-response']
